name: Deploy Backend

on:
  push:
    branches:
      - main  # O la rama principal de tu proyecto

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files after checkout
        run: ls -R

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'  # O la versión que estés usando

      # - name: Install dependencies
      #   run: npm install
      #   working-directory: ./Code/infochange/server

      # - name: Build backend
      #   run: npm run build
      #   working-directory: ./Code/infochange/server

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync backend folder to prod-backend
        run: |
          git clone --single-branch --branch prod-frontend https://x-access-token:${{ secrets.ANT_GITHUB_TOKEN }}@github.com/${{ github.repository }} prod-backend
          rm -r prod-backend/*
          cp -r ./Code/infochange/server/* prod-backend/
          cd prod-backend
          ls -la
          git add .
          git commit -m "Update backend deployment"
          git push origin prod-backend --force
