name: Deploy Backend

on:
  push:
    branches:
      - main  # O la rama principal de tu proyecto

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files after checkout
        run: ls -R

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync backend folder to prod-backend
        run: |
          git clone --single-branch --branch prod-backend https://x-access-token:${{ secrets.ANT_GITHUB_TOKEN }}@github.com/${{ github.repository }} prod-backend
          rm -r prod-backend/*
          cp -r ./Code/infochange/server/* prod-backend/
          cd prod-backend
          ls -la
          git add -A  # Agrega todos los cambios al índice
          git status  # Opcional: Muestra el estado de Git para depuración
          git commit -m "Update backend deployment" || echo "No changes to commit"
          git push origin prod-backend

  push_remote:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf prod-backend/
          git clone --single-branch --branch prod-backend https://x-access-token:${{ secrets.ANT_GITHUB_TOKEN }}@github.com/${{ github.repository }} prod-backend
          cd prod-backend
          npm install
          npm run set-env
          cd bin
          pm2 start www
          echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart nginx
          pm2 save

    
